---
  - user:
     name: bmwt
     shell: /bin/bash
     groups: sudo
     append: yes
    
  - lineinfile:
     path: /etc/hosts
     line: '{{ item.ip }} {{item.hostname}}' 
     state: present
     create: true
    with_items:
     - { hostname: 'magna.zero', ip: '10.5.0.111' }
     - { hostname: 'nauvoo.zero', ip: '10.5.0.133' }
     - { hostname: 'login.zero', ip: '10.5.0.148' }
     - { hostname: 'hera.zero', ip: '10.5.0.145' }
     - { hostname: 'odroid.zero', ip: '10.5.0.125' }
     - { hostname: 'magna-win.zero', ip: '10.5.0.116' }
     - { hostname: 'pizero.zero', ip: '10.5.0.102' }
     - { hostname: 'ds718.zero diskstation.zero synology.zero bob.zero', ip: '10.5.0.149' }
